name: CI

on:
  - workflow_dispatch
  - push

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
#          - macos
        compiler:
          - cc: gcc
            cxx: g++
          - cc: clang
            cxx: clang++
        shell:
          - bash
#        exclude:
#          - os: macos
#            compiler: { cc: gcc, cxx: g++ }
        include:
          - os: windows
            compiler: { cc: gcc, cxx: g++ }
            shell: msys2
            msystem: ucrt64
          - os: windows
            compiler: { cc: clang, cxx: clang++ }
            shell: msys2
            msystem: clang64
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: ${{ matrix.shell }} {0}
    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install dependencies
        if: ${{ matrix.os == 'ubuntu' }}
        run: sudo apt install ninja-build libtbb-dev libhwloc-dev libboost-program-options-dev
      - name: Install dependencies
        if: ${{ matrix.os == 'macos' }}
        run: |
          brew install ninja tbb hwloc boost
          echo "ZLIB_ROOT=$(brew --prefix zlib)" >> $GITHUB_ENV
      - name: Install dependencies
        if: ${{ matrix.os == 'windows' }}
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          pacboy: >-
            toolchain:p
            cmake:p
            ninja:p
            gmp:p
            tbb:p
            hwloc:p
            boost:p
      - name: Setup dependencies
        if: ${{ matrix.os == 'windows' }}
        run: mv /${{ matrix.msystem }}/lib/libtbb12.dll.a /${{ matrix.msystem }}/lib/libtbb.dll.a
      - name: Configure
        run: cmake -B build -G Ninja
      - name: Build
        run: cmake --build build
